---

- include: discover.yml
  when: groups['redis_server']|length > 0

- include: tuning.yml
  when:
    - redis_server is defined
    - redis_server|bool
  tags:
    - tuning

- include: install.yml
  tags:
    - install

- include: server.yml
  when:
    - redis_server is defined
    - redis_server|bool
  tags:
    - config

- include: sentinel.yml
  when: redis_sentinel is defined
  tags:
    - config

- include: verify.yml
  when: redis_sentinel is defined
  tags:
    - verify
