---
# handlers file for base_redis

- name: restart redis
  systemd:
    name: "{{ redis_daemon }}"
    state: restarted

- name: restart sentinel
  systemd:
    name: "{{ sentinel_daemon }}"
    state: restarted
