---
# Standards: 0.2
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: base-redis-centos7
    image: milcom/centos7-systemd
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
      stdout_callback: yaml
  playbooks:
    converge: converge.yml
    cleanup: cleanup.yml
  options:
    v: true
    diff: true
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: goss
  lint:
    name: yamllint
