---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: base-redis1-centos7
    image: milcom/centos7-systemd
    privileged: true
    groups:
      - redis_master
      - redis_sentinel
  - name: base-redis2-centos7
    image: milcom/centos7-systemd
    privileged: true
    groups:
      - redis_slave
      - redis_sentinel
  - name: base-redis3-centos7
    image: milcom/centos7-systemd
    privileged: true
    groups:
      - redis_slave
      - redis_sentinel
provisioner:
  name: ansible
verifier:
  name: ansible
